var $ci360;
(function(g){var l=function(){function e(){}e._keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-=";e.encode=function(a){for(var c="",b,d,h,f,n,p=0,m=e._utf8_encode(a);p<m.length;)b=m.charCodeAt(p++),a=m.charCodeAt(p++),d=m.charCodeAt(p++),h=b>>2,b=(b&3)<<4|a>>4,f=(a&15)<<2|d>>6,n=d&63,isNaN(a)?f=n=64:isNaN(d)&&(n=64),c=c+e._keyStr.charAt(h)+e._keyStr.charAt(b)+e._keyStr.charAt(f)+e._keyStr.charAt(n);return c};e._utf8_encode=function(a){a=a.replace(/\r\n/g,"\n");for(var c="",
b=0;b<a.length;b++){var d=a.charCodeAt(b);128>d?c+=String.fromCharCode(d):(127<d&&2048>d?c+=String.fromCharCode(d>>6|192):(c+=String.fromCharCode(d>>12|224),c+=String.fromCharCode(d>>6&63|128)),c+=String.fromCharCode(d&63|128))}return c};return e}();g.Base64=l})($ci360||($ci360={}));
(function(g){var l=function(){function e(a,c,b,d,h,f){this.configService=a;this.persistenceService=c;this.networkService=b;this.paramService=d;this.spotService=h;this.util=f}e.prototype.send=function(a,c){var b=this;void 0===c&&(c=!0);this.persistenceService.registerActivity();var d;a.hasOwnProperty("eventName")&&(d=a.eventName);var h=new g.CI360EventObj(d);this.addFieldsToEvent(h,a);this.decorateEvent(h);if(a=this.paramService.validateEvent(h))this.paramService.obfuscateFields(h),h.paramMap.delete("obfuscateFields"),
this.paramService.mapTransportNames(h),this.sendEvent(h,c),"identity"==d&&setTimeout(function(){return b.configService.retrieveDid()},e.RT_DID_TO);return a};e.prototype.addFieldsToEvent=function(a,c){"submit"===a.paramMap.get("eventName")&&this.paramService.submitEventHandling(a,c);"change"===a.paramMap.get("eventName")&&this.paramService.changeEventHandling(a,c);"cart"===a.paramMap.get("eventName")&&this.paramService.cartEventHandling(a,c);"load"===a.paramMap.get("eventName")&&this.networkService.setCachedLoadEvent(a);
for(var b in c)c.hasOwnProperty(b)&&"items"!==b&&a.paramMap.set(b,c[b])};e.prototype.sendEvent=function(a,c){c&&a.paramMap.set("initiator","api");a.paramMap.set("event_guid",this.networkService.getRandomGuid());"impression_viewable"===a.paramMap.get("eventName")?a.paramMap.set("event","spot_viewable"):a.paramMap.set("event",a.paramMap.get("eventName"));a.paramMap.set("eventname",a.paramMap.get("eventName"));this.networkService.pushEvent(a)};e.prototype.decorateEvent=function(a){var c=this.configService.getConfig();
a.paramMap.set("tab_id",this.persistenceService.getTabId());a.paramMap.set("hb",this.persistenceService.getSidArray()[2]);var b={ccs:"ccs",csu:"csu",datahubId:"datahub_id",vid:"visitor",sid:"session"},d;for(d in b)a.paramMap.set(b[d],c[d]);"load"!=a.paramMap.get("eventName")&&a.paramMap.set("load_id",this.networkService.getLoadId());this.spotService.decorateEvent(a);this.paramService.addDefaultFields(a)};e.RT_DID_TO=1500;return e}();g.EventService=l})($ci360||($ci360={}));
(function(g){var l=function(){function e(){this.readyCallbacks=[];this.isReady=!1;this.initError=null;this.initStarted=!1;this.services=[];this.efname="ci360";this.lazyInit=!1}e.prototype.updateExposedFunction=function(){var a=this,c=this.ef&&this.ef.q,b=window[this.efname]=function(){for(var b=[],c=0;c<arguments.length;c++)b[c]=arguments[c];return a.api[b[0]]?a.api[b[0]](b[1],b[2]):"Not able to perform "+b[0]+" on ci360()"};if(c){for(var d=0;d<c.length;d++)b.apply(void 0,c[d]);c.length=0}};e.prototype.notifyReady=
function(){this.isReady=!0;for(var a=0,c=this.readyCallbacks;a<c.length;a++)(0,c[a])(this.initError);this.readyCallbacks.length=0};e.prototype.notifyError=function(a){this.initError=a;this.notifyReady()};e.prototype.addReadyCallback=function(a){this.isReady?a(this.initError):this.readyCallbacks.push(a)};e.prototype.done=function(a){var c=this;null==a?0<this.services.length?this.services.shift().init(function(b){return c.done(b)}):this.notifyReady():this.notifyError(a)};e.prototype.require=function(){for(var a=
[],c=0;c<arguments.length;c++)a[c]=arguments[c];if(!this.initStarted&&a)for(c=0;c<a.length;c++)this.services.push(a[c])};e.prototype.initialize=function(){this.initStarted||this.lazyInit||(this.initStarted=!0,this.done())};e.prototype.createApi=function(a,c,b,d){var h=this;this.api={ready:function(b){h.addReadyCallback(b)},send:function(a){return b.send(a)},detachIdentity:function(){return a.detachIdentity()},attachIdentity:function(b){return a.attachIdentity(b)},trace:function(b){return a.trace(b)},
info:function(){var b={},d=a.getConfig();b.datahubId=a.getDatahubId();b.vid=d.vid;b.sid=d.sid;b.loadId=a.getLoadId();g.exposeParamsMetadata=!0;g.exposeParamsMetadata&&(b.params_metadata=c.getParamsMetadata());return b},getCreatives:function(b,a){return d.getCreatives(b,!0,a)},getPersonalizedCreative:function(b,a){return d.getPersonalizedCreative(b,a)},getSpotDefinitions:function(b,a){return d.getSpotDefinitions(b,a)},init:function(){h.initialize()}}};e.prototype.getEnvironmentAttributes=function(){var a=
this;if(null==this.envAttrs){this.envAttrs={};var c=document.getElementById("ob-script-async");if(null!=c){this.efname=c.dataset.efname||this.efname;var b=(this.ef=window[this.efname])&&this.ef.a&&JSON.parse(JSON.stringify(this.ef.a))||{},d=c.getAttribute("src"),h=document.createElement("a");h.href=d;this.envAttrs.protocol=h.protocol;this.envAttrs.hostname=h.hostname;this.envAttrs.port=h.port;this.envAttrs.extTenantId=b.tenantId&&b.tenantId.trim()||c.getAttribute("a")&&c.getAttribute("a").trim()||
c.getAttribute("data-a")&&c.getAttribute("data-a").trim();this.envAttrs.extTenantId||(c=this.ef&&this.ef.q)&&0<c.length&&"settings"===c[0][0]&&(b=c.shift()[1],this.envAttrs.extTenantId=b.tenantId&&b.tenantId.trim());if(this.envAttrs.extTenantId)this.envAttrs.hiddenClass=b.hiddenClass,this.envAttrs.overrideDomain=b.overrideDomain,b.identity&&(this.envAttrs.identityType=b.identity.type,this.envAttrs.identitySource=b.identity.source||"cookie",this.envAttrs.identityName=b.identity.name,this.envAttrs.identityObscure=
b.identity.obscure||!1),b.trace&&(this.envAttrs.traceDoamins=b.trace.domains);else throw Error("TenantId missing.");this.readyCallbacks.push(function(){return a.updateExposedFunction()})}}return this.envAttrs};e.prototype.setLazyInit=function(a){void 0===a&&(a=!1);if(this.lazyInit=a){var c=this;this.ef&&this.ef.q&&Object.defineProperty(this.ef.q,"push",{enumerable:!1,configurable:!1,writable:!1,value:function(b){0<b.length&&"init"===b[0]?(c.lazyInit=!1,c.initialize()):this[this.length]=b;return this.length}})}};
return e}();g.Bootstrap=l})($ci360||($ci360={}));
(function(g){var l=function(){function e(a){this.paramMap=new Map;this.obscureCount=0;null!=a&&this.paramMap.set("eventName",a)}e.prototype.populate=function(a){a=JSON.parse(a);for(var c in a)this.paramMap.set(c,a[c])};e.prototype.toJSONString=function(){return JSON.stringify(this)};e.prototype.toJSON=function(){var a={};this.paramMap.forEach(function(c,b){a[b]=c});return a};e.prototype.toURLEncoded=function(){var a="";this.paramMap.forEach(function(c,b){a+=encodeURIComponent(b)+"="+encodeURIComponent(c)+
"&"});return a.slice(0,a.length-1)};return e}();g.CI360EventObj=l})($ci360||($ci360={}));
(function(g){var l=function(){function e(a,c,b,d,h){var f=this;this.serverInfo={protocol:"",hostname:"",port:""};this.identityAtLoad=!1;this.traceDomains=[];this.config={vid:"",sid:"",timestamp:"",isNewVid:!1,isNewSid:!1,datahubId:"",loadId:"",ccs:"",csu:"",sdu:"",sld:"",e:void 0,f:void 0,s:void 0,c:void 0,t:{},l:void 0};this.hiddenClass="sas-ci360-hidden";this.ciParam="_ci_";this.inDesignCenter=!1;this.traceForm=function(b){try{if(b&&"FORM"==b.tagName.toUpperCase()&&b.action){var a=window.location,
c=a.hostname||a.host,d=f.util.extractDomain(b.action);if(d&&-1<f.traceDomains.indexOf(d)&&c!=d){a=!1;c=0;for(var h=b.elements;c<h.length;c++)h[c].name==f.ciParam&&(a=!0);if(b.method)if("GET"!=b.method.toUpperCase()||a)"POST"==b.method.toUpperCase()&&(b.action=f.trace(b.action));else{var n=document.createElement("input");n.setAttribute("type","hidden");n.setAttribute("name",f.ciParam);n.setAttribute("value",f.cdtToken());b.appendChild(n)}}}}catch(x){}};this.traceAnchor=function(b){try{var a=void 0;
a:{for(var c=100;b&&0<c;){if(b.href&&b.nodeName.match(/^a(?:rea)?$/i)){a=b;break a}b=b.parentNode;c--}a=null}if(a){var d=window.location,h=d.hostname||d.host,n=a.host||a.hostname;if(n&&-1<f.traceDomains.indexOf(n)&&h!=n){var e=a.protocol,g=a.href;("http:"==e||"https:"==e)&&0>g.indexOf(f.ciParam)&&(a.href=f.trace(g))}}}catch(w){}};this.trace=function(b){return b+(0<b.indexOf("?")?"&":"?")+f.ciParam+"="+f.cdtToken()};this.cdtToken=function(){var b=f.persistenceService,a=b.getSidArray();return b.getVid()+
"*"+a[0]+"*"+a[2]+"*"+f.paramService.getUsrAgent()+"*"+(new Date).getTime()+"*"+(screen.height||"1")+(screen.width||"1")};this.cdtInfo=function(b){try{var a=decodeURIComponent(b).split("*")||"";return(6==a.length&&a[3]==f.paramService.getUsrAgent()&&parseInt(a[4])+1E4>(new Date).getTime()&&(screen.height||"1")+""+(screen.width||"1")==a[5]&&a[0]&&a[1]||4==a.length&&parseInt(a[3])+1E4>(new Date).getTime())&&{vid:a[0],sid:a[1],hb:a[2],ref:4==a.length?"1":"0"}||null}catch(m){return null}};this.cdtInfoPage=
function(){var b=f.util.getUriInfo().cdt;return b&&f.cdtInfo(b)};this.updateNetworkService=!1;this.networkServiceObserver=function(){f.updateNetworkService=!0};this.refreshConfig=function(b,a){f.networkService.setFirstLoad(!0);f.networkService.call(f.buildConfigURL(!0),function(c){f.configLoadCallback(c);a();b()})};this.getAttributeStore=function(b){if(b||void 0===f.cachedAttributeStore){b={};b.browser_language=navigator.language;var a=!1;if(navigator.plugins&&navigator.plugins.length){var c=navigator.plugins["Shockwave Flash"];
c||(c=navigator.plugins["Shockwave Flash 2.0"]);c&&(a=!0)}b.flash_enabled=a.toString();b.character_set=document.characterSet;b.event_channel="web";b.java_enabled=navigator.javaEnabled().toString();b.platform=navigator.platform;b.protocol=location.protocol.substr(0,location.protocol.length-1);return f.cachedAttributeStore=b}return f.cachedAttributeStore};this.handleConfig=function(b){var a=f.networkService;f.config.sid=b.sid||"";f.config.vid=b.vid||"";f.config.timestamp=b.timestamp||"";f.config.isNewSid=
b.isNewSid||!1;f.config.isNewVid=b.isNewVid||!1;f.config.datahubId=b.datahubId||"";f.config.loadId=b.loadId||"";a.setLoadId(f.config.loadId);f.config.csu=b.csu||"";f.config.sld=b.sld||"";f.config.e=b.e;f.config.f=b.f;f.persistenceService.setSld(f.config.sld);a.setSessionId(f.config.sid);a.setClientBaseTimestamp((new Date).getTime());a.setServerTimestamp(parseInt(f.config.timestamp,10));f.config.s=b.s;f.config.c=b.c;f.config.t=b.t;f.config.l=b.l};this.getLoadId=function(){return f.networkService.getLoadId()};
this.setCookies=function(b){var a=f.persistenceService;a.setVid(b.vid);a.setSid(b.sid);a.setDid(b.datahubId)};this.configLoadCallback=function(b){b=JSON.parse(b);f.handleConfig(b);f.setCookies(b);f.traceDomains=(f.traceDomains||[]).concat(f.config.t&&f.config.t.d||[]);0<f.traceDomains.length&&(document.addEventListener("mousedown",function(b){f.traceAnchor(b.target||b.target||{})}),document.addEventListener("keyup",function(b){f.traceAnchor(b.target||b.target||{})}),document.addEventListener("submit",
function(b){f.traceForm(b.target||b.target||{})}));f.updateNetworkService?(f.updateNetworkService=!1,f.networkService.synthLoaded(!0),f.networkService.processEvents(!1)):f.networkService.processEvents();f.identityAtLoad?f.persistenceService.removeIdentityEvent():f.networkService.processIdentity(f.buildDatahubURL(),f.updateDid)};this.buildIdentity=function(b){var a=f.persistenceService,c=f.paramService,d=f.networkService,h=new g.CI360EventObj("identity"),e=f.getConfig(),n="Unable to populate loginId.",
l=f.getConfig().timestamp||(new Date).getTime();d.getLoadId()&&h.paramMap.set("load_id",d.getLoadId());h.paramMap.set("domain",d.getDomain());h.paramMap.set("timestamp",l.toString());h.paramMap.set("tab_id",a.getTabId());h.paramMap.set("hb",a.getSidArray()[2]);d={sid:"session",vid:"visitor"};for(var w in d)e[w]&&h.paramMap.set(d[w],e[w]);!b&&f.identityType&&f.identityName&&(b={url:function(){return f.util.extractParam(f.identityName,window.location.href)},jsvar:function(){return f.util.getJsVarValueSafe(f.identityName)},
"default":function(){return a.getCookie(f.identityName)}},b={loginEventType:f.identityType,loginId:(b[f.identitySource]||b["default"])(),obfuscateFields:"["+(f.identityObscure&&'"loginId"'||'""')+"]"});return b&&b.loginId&&(c.addFieldsToEvent(h,b),c.validateEvent(h))?(n="success",c.obfuscateFields(h),c.mapTransportNames(h),h.paramMap.delete("eventName"),[h.toURLEncoded(),h.paramMap.get("login_event")+h.paramMap.get("login_event_type"),n]):[null,null,n]};this.retrieveDid=function(){f.networkService.call(f.buildDatahubURL(),
f.updateDid)};this.updateDid=function(b){null!=b&&/^([0-9]|[a-z]|[A-Z]|-){24,256}$/.test(b)&&(f.persistenceService.setDid(b),f.config.datahubId=b)};this.getDatahubId=function(){return f.persistenceService.getDid()||f.config.datahubId};this.persistenceService=a;this.networkService=c;this.paramService=b;this.util=d;this.isOt2=h;this.networkService.addObserver(this.networkServiceObserver)}e.prototype.getHiddenClass=function(){return this.hiddenClass};e.prototype.getThresholds=function(){return this.config.s?
this.config.s:[]};e.prototype.checkForDesignCenter=function(){var a=this;if(0==window.frames.name.indexOf("inlineBrowserIFrame-")){this.inDesignCenter=!0;var c=this.serverInfo,b=c.protocol,d=c.hostname,h=c.port;h=h?":"+h:"";this.addScript(b+"//"+d+h+"/js/jquery.min.js","uisupport_jquery");setTimeout(function(){a.addScript(b+"//"+d+h+"/js/content.js","uisupport_content")},500)}};e.prototype.addScript=function(a,c){var b=document;if(!b.getElementById(c)){var d=b.getElementsByTagName("script")[0];b=
b.createElement("script");b.async=!0;b.src=a;c&&(b.id=c);d.parentNode.insertBefore(b,d)}};e.prototype.getFormConfig=function(){this.config&&this.config.f&&(this.config.f.ign&&this.config.f.ign.n&&"ign"===this.config.f.ign.n?this.config.f.n="ign":this.config.f.inc&&this.config.f.inc.n&&"inc"===this.config.f.inc.n&&(this.config.f.n="inc"));return this.config.f};e.prototype.setEnvironmentAttributes=function(a){void 0===a&&(a={});this.serverInfo.protocol=a.protocol||"";this.serverInfo.hostname=a.hostname||
"";this.serverInfo.port=a.port||"";this.extTenantId=a.extTenantId||"";this.networkService.setExtTenantId(this.extTenantId);this.paramService.setExtTenantId(this.extTenantId);this.persistenceService.setExtTenantId(this.extTenantId);this.identityType=a.identityType||"";this.identityName=a.identityName||"";this.identitySource=a.identitySource||"";this.identityObscure=a.identityObscure||!1;this.traceDomains=a.traceDoamins||[];this.networkService.setOverrideDomain(a.overrideDomain);this.config.ccs=this.serverInfo.protocol+
"//"+this.serverInfo.hostname+":"+this.serverInfo.port+"/t/e/"+this.extTenantId;this.networkService.setCcs(this.config.ccs);this.config.sdu=this.serverInfo.protocol+"//"+this.serverInfo.hostname+":"+this.serverInfo.port+"/t/s/p/"+this.extTenantId;a.hiddenClass&&(this.hiddenClass=a.hiddenClass)};e.prototype.buildConfigURL=function(a){void 0===a&&(a=!1);var c=this.getAttributeStore(),b=this.persistenceService,d=this.serverInfo.protocol+"//"+this.serverInfo.hostname+":"+this.serverInfo.port+"/t/s/c/"+
this.extTenantId,h="domain="+this.networkService.getDomain(),f=this.cdtInfoPage(),e="";if(f&&f.vid&&f.sid){var p=f.vid;var m=f.sid;var k=f.hb||0;e="&cdt=o&cdtref="+f.ref}else p=b.getVid(),k=b.getSidArray(),m=k[0],k=k[2];p=p?"&vid="+p:"";m=m?"&sid="+m+"&hb="+k:"";k="";a||(k=(k=(k=window.com_sas_ci_acs)&&k.ob_configure&&k.ob_configure.getLoadId())?"&loadId="+k:"");var u=this.util.getUriInfo();a="&p="+encodeURIComponent(u.path);f="&params="+encodeURIComponent(u.search);var g="&page_title="+encodeURIComponent(document.title),
x="&referrer="+encodeURIComponent(document.referrer),l="&uri="+encodeURIComponent(document.URL),w=new Date,q="&cts="+w.getTime();w="&tzo="+w.getTimezoneOffset();var C="&platform="+navigator.platform,y="&port="+location.port;u="&protocol="+u.protocol;var t="&screen_info="+screen.width+"x"+screen.height+"@"+screen.colorDepth,G="&browser_language="+c.browser_language,D="&character_set="+c.character_set,N="&csz="+document.documentElement.outerHTML.length,z="&bsz="+window.innerWidth+"x"+window.innerHeight;
b="&tab_id="+b.getTabId();var E="&java_enabled="+c.java_enabled;c="&flash_enabled="+c.flash_enabled;var F="";this.isOt2&&(F="&init=ot2&version=2.1");return d+"?"+h+e+p+m+k+a+f+g+x+l+q+w+C+y+u+t+G+D+N+z+b+E+c+F+(this.inDesignCenter?"&swm=1":"")};e.prototype.init=function(a){var c=this.buildIdentity()[0];this.identityAtLoad=!!c;this.checkForDesignCenter();this.networkService.call(this.buildConfigURL(),this.configLoadCallback,a,c&&"POST"||"GET",c)};e.prototype.getContentChangeInfo=function(){var a=[];
if(this.config&&this.config.e&&this.config.e.cc)for(var c=0;c<this.config.e.cc.length;c++){var b=this.config.e.cc[c],d={};d.eventuid=b[0];d.selector=b[1];a.push(d)}return a};e.prototype.getJsVarsToObserve=function(){var a=[];if(this.config&&this.config.e)var c=this.config.e.jsc;if(c)for(var b=0;b<c.length;b++)a.push(c[b][0]);return a};e.prototype.getCartConfiguration=function(){var a={cart:"cartview"},c=[],b=this.config&&this.config.e&&this.config.e.cart;if(b)for(var d=0;d<b.length;d++){var h=b[d];
c.push({rowSelector:h.s,action:a[h.t]||h.t,details:h.d,productAttributes:h.i,internalCartId:h.id,name:h.n,removeRules:h.r})}return c};e.prototype.attachIdentity=function(a){a=this.buildIdentity(a);a[0]&&a[1]&&this.networkService.processIdentity(this.buildDatahubURL(),this.updateDid,a[0],a[1]);return a[2]};e.prototype.detachIdentity=function(){this.networkService.processIdentity(this.buildDatahubURL(),this.updateDid,"D","D")};e.prototype.buildDatahubURL=function(){return this.serverInfo.protocol+"//"+
this.serverInfo.hostname+":"+this.serverInfo.port+"/t/s/d/"+this.extTenantId+"/"+this.getConfig().vid};e.prototype.getConfig=function(){this.config.datahubId=this.persistenceService.getDid()||this.config.datahubId;return this.config};e.prototype.isInDesignCenter=function(){return this.inDesignCenter};e.prototype.getPageElements=function(){return this.config&&this.config.e&&this.config.e.term?this.config.e.term:[]};e.prototype.getJsVars=function(){return this.config&&this.config.e&&this.config.e.jsv?
this.config.e.jsv:[]};e.prototype.getCollectRules=function(){if(this.config.c)return this.config.c};e.prototype.getIdentityEventConfigs=function(){if(this.config&&this.config.e&&this.config.e.id){for(var a={pageView:[],click:[],formSubmit:[]},c=0;c<this.config.e.id.length;c++){var b=this.config.e.id[c];"pageView"===b.t?a.pageView.push(b):"click"===b.t?a.click.push(b):"formSubmit"===b.t&&a.formSubmit.push(b)}return a}};e.prototype.getLoadRules=function(){if(this.config.l)return this.config.l};return e}();
g.ConfigService=l})($ci360||($ci360={}));
(function(g){var l=function(){function e(){this.forge=this.initForge()}e.prototype.sha384=function(a){var c=this.forge.md.sha384.create();c.update(a);return c.digest().toHex()};e.prototype.initForge=function(){function a(b){this.data="";this.read=0;if("string"===typeof b)this.data=b;else if(b instanceof a||"object"===typeof b&&"string"===typeof b.data&&"number"===typeof b.read)this.data=b.data,this.read=b.read;this._constructedStringLength=0}function c(b,a,c){for(var d,f,h,e,k,n,m,u,g,r,l,E,F,J,O,
P,A,B,K,L,H,I,Q,R,v,S=c.length();128<=S;){for(v=0;16>v;++v)a[v][0]=c.getInt32()>>>0,a[v][1]=c.getInt32()>>>0;for(;80>v;++v)k=a[v-2],g=k[0],k=k[1],d=((g>>>19|k<<13)^(k>>>29|g<<3)^g>>>6)>>>0,f=((g<<13|k>>>19)^(k<<3|g>>>29)^(g<<26|k>>>6))>>>0,k=a[v-15],g=k[0],k=k[1],h=((g>>>1|k<<31)^(g>>>8|k<<24)^g>>>7)>>>0,e=((g<<31|k>>>1)^(g<<24|k>>>8)^(g<<25|k>>>7))>>>0,g=a[v-7],r=a[v-16],k=f+g[1]+e+r[1],a[v][0]=d+g[0]+h+r[0]+(k/4294967296>>>0)>>>0,a[v][1]=k>>>0;g=b[0][0];r=b[0][1];l=b[1][0];E=b[1][1];F=b[2][0];J=
b[2][1];O=b[3][0];P=b[3][1];A=b[4][0];B=b[4][1];K=b[5][0];L=b[5][1];H=b[6][0];I=b[6][1];Q=b[7][0];R=b[7][1];for(v=0;80>v;++v)d=((A>>>14|B<<18)^(A>>>18|B<<14)^(B>>>9|A<<23))>>>0,k=((A<<18|B>>>14)^(A<<14|B>>>18)^(B<<23|A>>>9))>>>0,f=(H^A&(K^H))>>>0,n=(I^B&(L^I))>>>0,h=((g>>>28|r<<4)^(r>>>2|g<<30)^(r>>>7|g<<25))>>>0,e=((g<<4|r>>>28)^(r<<30|g>>>2)^(r<<25|g>>>7))>>>0,m=(g&l|F&(g^l))>>>0,u=(r&E|J&(r^E))>>>0,k=R+k+n+p[v][1]+a[v][1],d=Q+d+f+p[v][0]+a[v][0]+(k/4294967296>>>0)>>>0,f=k>>>0,k=e+u,h=h+m+(k/4294967296>>>
0)>>>0,e=k>>>0,Q=H,R=I,H=K,I=L,K=A,L=B,k=P+f,A=O+d+(k/4294967296>>>0)>>>0,B=k>>>0,O=F,P=J,F=l,J=E,l=g,E=r,k=f+e,g=d+h+(k/4294967296>>>0)>>>0,r=k>>>0;k=b[0][1]+r;b[0][0]=b[0][0]+g+(k/4294967296>>>0)>>>0;b[0][1]=k>>>0;k=b[1][1]+E;b[1][0]=b[1][0]+l+(k/4294967296>>>0)>>>0;b[1][1]=k>>>0;k=b[2][1]+J;b[2][0]=b[2][0]+F+(k/4294967296>>>0)>>>0;b[2][1]=k>>>0;k=b[3][1]+P;b[3][0]=b[3][0]+O+(k/4294967296>>>0)>>>0;b[3][1]=k>>>0;k=b[4][1]+B;b[4][0]=b[4][0]+A+(k/4294967296>>>0)>>>0;b[4][1]=k>>>0;k=b[5][1]+L;b[5][0]=
b[5][0]+K+(k/4294967296>>>0)>>>0;b[5][1]=k>>>0;k=b[6][1]+I;b[6][0]=b[6][0]+H+(k/4294967296>>>0)>>>0;b[6][1]=k>>>0;k=b[7][1]+R;b[7][0]=b[7][0]+Q+(k/4294967296>>>0)>>>0;b[7][1]=k>>>0;S-=128}}var b=b||{};b.md=b.md||{};b.md.algorithms=b.md.algorithms||{};var d=b.sha512=b.sha512||{};b.util=b.util||{};b.util.fillString=function(b,a){for(var c="";0<a;)a&1&&(c+=b),a>>>=1,0<a&&(b+=b);return c};b.util.createBuffer=function(a,c){void 0!==a&&"utf8"===(c||"raw")&&(a=b.util.encodeUtf8(a));return new b.util.ByteBuffer(a)};
b.util.encodeUtf8=function(b){return unescape(encodeURIComponent(b))};b.util.ByteBuffer=a;b.util.isArrayBuffer=function(b){return"undefined"!==typeof ArrayBuffer&&b instanceof ArrayBuffer};b.util.isArrayBufferView=function(a){return a&&b.util.isArrayBuffer(a.buffer)&&void 0!==a.byteLength};b.util.ByteStringBuffer=a;b.util.ByteStringBuffer.prototype._optimizeConstructedString=function(b){this._constructedStringLength+=b;4096<this._constructedStringLength&&(this.data.substr(0,1),this._constructedStringLength=
0)};b.util.ByteStringBuffer.prototype.length=function(){return this.data.length-this.read};b.util.ByteStringBuffer.prototype.isEmpty=function(){return 0>=this.length()};b.util.ByteStringBuffer.prototype.putBytes=function(b){this.data+=b;this._optimizeConstructedString(b.length);return this};b.util.ByteStringBuffer.prototype.putInt32=function(b){return this.putBytes(String.fromCharCode(b>>24&255)+String.fromCharCode(b>>16&255)+String.fromCharCode(b>>8&255)+String.fromCharCode(b&255))};b.util.ByteStringBuffer.prototype.putInt=
function(b,a){if(8!==a&&16!==a&&24!==a&&32!==a)throw Error("Only 8, 16, 24, or 32 bits supported: "+a);var c="";do a-=8,c+=String.fromCharCode(b>>a&255);while(0<a);return this.putBytes(c)};b.util.ByteStringBuffer.prototype.getInt16=function(){var b=this.data.charCodeAt(this.read)<<8^this.data.charCodeAt(this.read+1);this.read+=2;return b};b.util.ByteStringBuffer.prototype.getInt32=function(){var b=this.data.charCodeAt(this.read)<<24^this.data.charCodeAt(this.read+1)<<16^this.data.charCodeAt(this.read+
2)<<8^this.data.charCodeAt(this.read+3);this.read+=4;return b};b.util.ByteStringBuffer.prototype.bytes=function(b){return"undefined"===typeof b?this.data.slice(this.read):this.data.slice(this.read,this.read+b)};b.util.ByteStringBuffer.prototype.at=function(b){return this.data.charCodeAt(this.read+b)};b.util.ByteStringBuffer.prototype.setAt=function(b,a){this.data=this.data.substr(0,this.read+b)+String.fromCharCode(a)+this.data.substr(this.read+b+1);return this};b.util.ByteStringBuffer.prototype.last=
function(){return this.data.charCodeAt(this.data.length-1)};b.util.ByteStringBuffer.prototype.copy=function(){var a=b.util.createBuffer(this.data);a.read=this.read;return a};b.util.ByteStringBuffer.prototype.compact=function(){0<this.read&&(this.data=this.data.slice(this.read),this.read=0);return this};b.util.ByteStringBuffer.prototype.clear=function(){this.data="";this.read=0;return this};b.util.ByteStringBuffer.prototype.toHex=function(){for(var b="",a=this.read;a<this.data.length;++a){var c=this.data.charCodeAt(a);
16>c&&(b+="0");b+=c.toString(16)}return b};b.util.ByteStringBuffer.prototype.toString=function(){return b.util.decodeUtf8(this.bytes())};b.md.sha512=b.md.algorithms.sha512=d;var h=b.sha384=b.sha512.sha384=b.sha512.sha384||{};h.create=function(){return d.create("SHA-384")};b.md.sha384=b.md.algorithms.sha384=h;b.sha512.sha256=b.sha512.sha256||{create:function(){return d.create("SHA-512/256")}};b.md["sha512/256"]=b.md.algorithms["sha512/256"]=b.sha512.sha256;b.sha512.sha224=b.sha512.sha224||{create:function(){return d.create("SHA-512/224")}};
b.md["sha512/224"]=b.md.algorithms["sha512/224"]=b.sha512.sha224;d.create=function(a){e||(f=String.fromCharCode(128),f+=b.util.fillString(String.fromCharCode(0),128),p=[[1116352408,3609767458],[1899447441,602891725],[3049323471,3964484399],[3921009573,2173295548],[961987163,4081628472],[1508970993,3053834265],[2453635748,2937671579],[2870763221,3664609560],[3624381080,2734883394],[310598401,1164996542],[607225278,1323610764],[1426881987,3590304994],[1925078388,4068182383],[2162078206,991336113],[2614888103,
633803317],[3248222580,3479774868],[3835390401,2666613458],[4022224774,944711139],[264347078,2341262773],[604807628,2007800933],[770255983,1495990901],[1249150122,1856431235],[1555081692,3175218132],[1996064986,2198950837],[2554220882,3999719339],[2821834349,766784016],[2952996808,2566594879],[3210313671,3203337956],[3336571891,1034457026],[3584528711,2466948901],[113926993,3758326383],[338241895,168717936],[666307205,1188179964],[773529912,1546045734],[1294757372,1522805485],[1396182291,2643833823],
[1695183700,2343527390],[1986661051,1014477480],[2177026350,1206759142],[2456956037,344077627],[2730485921,1290863460],[2820302411,3158454273],[3259730800,3505952657],[3345764771,106217008],[3516065817,3606008344],[3600352804,1432725776],[4094571909,1467031594],[275423344,851169720],[430227734,3100823752],[506948616,1363258195],[659060556,3750685593],[883997877,3785050280],[958139571,3318307427],[1322822218,3812723403],[1537002063,2003034995],[1747873779,3602036899],[1955562222,1575990012],[2024104815,
1125592928],[2227730452,2716904306],[2361852424,442776044],[2428436474,593698344],[2756734187,3733110249],[3204031479,2999351573],[3329325298,3815920427],[3391569614,3928383900],[3515267271,566280711],[3940187606,3454069534],[4118630271,4000239992],[116418474,1914138554],[174292421,2731055270],[289380356,3203993006],[460393269,320620315],[685471733,587496836],[852142971,1086792851],[1017036298,365543100],[1126000580,2618297676],[1288033470,3409855158],[1501505948,4234509866],[1607167915,987167468],
[1816402316,1246189591]],m={"SHA-512":[[1779033703,4089235720],[3144134277,2227873595],[1013904242,4271175723],[2773480762,1595750129],[1359893119,2917565137],[2600822924,725511199],[528734635,4215389547],[1541459225,327033209]],"SHA-384":[[3418070365,3238371032],[1654270250,914150663],[2438529370,812702999],[355462360,4144912697],[1731405415,4290775857],[2394180231,1750603025],[3675008525,1694076839],[1203062813,3204075428]],"SHA-512/256":[[573645204,4230739756],[2673172387,3360449730],[596883563,
1867755857],[2520282905,1497426621],[2519219938,2827943907],[3193839141,1401305490],[721525244,746961066],[246885852,2177182882]],"SHA-512/224":[[2352822216,424955298],[1944164710,2312950998],[502970286,855612546],[1738396948,1479516111],[258812777,2077511080],[2011393907,79989058],[1067287976,1780299464],[286451373,2446758561]]},e=!0);"undefined"===typeof a&&(a="SHA-512");if(!(a in m))throw Error("Invalid SHA-512 algorithm: "+a);for(var d=m[a],h=null,k=b.util.createBuffer(),n=Array(80),g=0;80>g;++g)n[g]=
Array(2);g=64;switch(a){case "SHA-384":g=48;break;case "SHA-512/256":g=32;break;case "SHA-512/224":g=28}var q={algorithm:a.replace("-","").toLowerCase(),blockLength:128,digestLength:g,messageLength:0,fullMessageLength:null,messageLengthSize:16,messageLength128:null,update:null,digest:null,start:function(){q.messageLength=0;q.fullMessageLength=q.messageLength128=[];for(var a=q.messageLengthSize/4,c=0;c<a;++c)q.fullMessageLength.push(0);k=b.util.createBuffer();h=Array(d.length);for(c=0;c<d.length;++c)h[c]=
d[c].slice(0);return q}};q.start();q.update=function(a,d){"utf8"===d&&(a=b.util.encodeUtf8(a));d=a.length;q.messageLength+=d;d=[d/4294967296>>>0,d>>>0];for(var f=q.fullMessageLength.length-1;0<=f;--f)q.fullMessageLength[f]+=d[1],d[1]=d[0]+(q.fullMessageLength[f]/4294967296>>>0),q.fullMessageLength[f]>>>=0,d[0]=d[1]/4294967296>>>0;k.putBytes(a);c(h,n,k);(2048<k.read||0===k.length())&&k.compact();return q};q.digest=function(){var d=b.util.createBuffer();d.putBytes(k.bytes());d.putBytes(f.substr(0,q.blockLength-
(q.fullMessageLength[q.fullMessageLength.length-1]+q.messageLengthSize&q.blockLength-1)));for(var e,g,m=8*q.fullMessageLength[0],p=0;p<q.fullMessageLength.length-1;++p)e=8*q.fullMessageLength[p+1],g=e/4294967296>>>0,m+=g,d.putInt32(m>>>0),m=e>>>0;d.putInt32(m);e=Array(h.length);for(p=0;p<h.length;++p)e[p]=h[p].slice(0);c(e,n,d);d=b.util.createBuffer();g="SHA-512"===a?e.length:"SHA-384"===a?e.length-2:e.length-4;for(p=0;p<g;++p)d.putInt32(e[p][0]),p===g-1&&"SHA-512/224"===a||d.putInt32(e[p][1]);return d};
return q};var f=null,e=!1,p=null,m=null;return b};return e}();g.EncodingService=l})($ci360||($ci360={}));
(function(g){var l=function(){function e(a,c){var b=this;this.setExtTenantId=function(a){b.key+=a};this.DELIMITER=String.fromCharCode(127);this.size=0;this.key=a;this.storageType=c}e.prototype.storage=function(){return g[this.storageType]};e.prototype.retrieveItem=function(a){a=a?a:this.key;var c=this.storage().getItem(a);return c?c:(this.storage().setItem(a,""),"")};e.prototype.push=function(a){try{var c=a.toJSONString(),b=this.retrieveItem(this.key);b+=""==b?c:this.DELIMITER+c;this.storage().setItem(this.key,
b);this.size++}catch(d){return!1}return!0};e.prototype.pop=function(a){void 0===a&&(a=!1);try{var c=this.retrieveItem(this.key),b=c.indexOf(this.DELIMITER);if(-1<b){var d=c.substr(0,b);c=c.substr(b+1);this.storage().setItem(this.key,c);this.size--;if(a){var h=new g.CI360EventObj;h.populate(d);return h}}else if(0<c.length&&(this.storage().setItem(this.key,""),this.size=0,a))return h=new g.CI360EventObj,h.populate(c),h;return null}catch(f){return null}};e.prototype.getFront=function(){try{var a=this.retrieveItem(this.key),
c=a.indexOf(this.DELIMITER);if(-1<c){var b=a.substr(0,c),d=new g.CI360EventObj;d.populate(b);return d}return 0<a.length?(d=new g.CI360EventObj,d.populate(a),d):null}catch(h){return null}};return e}();g.LocalQueue=l})($ci360||($ci360={}));
(function(g){var l=function(){function e(a,c){var b=this;this.maxResendCount=3;this.resendCount=0;this.sendLock=!1;this.initialTimeout=1500;this.bodyInHeaderLoad=this.bodyInHeaderAll=!1;this.latestIdentity=null;this.synthLoad=!1;this.com_sas_ci_acs=window.com_sas_ci_acs;this.legacyTagLoaded=!1;this.firstLoad=!0;this.loadIdChanging=!1;this.getLoadId=function(){return b.loadId};this.setLoadId=function(a){b.loadId=a;b.legacyTagLoaded&&(b.com_sas_ci_acs.ob_configure.getLoadId=function(){return a})};this.setOverrideDomain=
function(a){b.overrideDomain=a};this.getDomain=function(){return"undefined"!==typeof com_sas_ci_acs&&com_sas_ci_acs.overrideDomain||b.overrideDomain||document.domain||""};this.getRandomGuid=function(){return b.loadId+Math.floor(1E12*Math.random()+1)};this.setSessionId=function(a){b.sessionId=a};this.observers=[];this.setExtTenantId=function(a){b.q.setExtTenantId(a)};this.setCcs=function(a){b.ccs=a};this.unlocked=function(){return!1===b.sendLock};this.call=function(b,a,c,e,g){void 0===a&&(a=function(){});
void 0===c&&(c=function(){});void 0===e&&(e="GET");var d=new XMLHttpRequest;d.onreadystatechange=function(){d.readyState===XMLHttpRequest.DONE&&200<=d.status&&300>d.status?d.responseText?(a(d.responseText),c()):c(Error("Response is Empty.")):d.readyState===XMLHttpRequest.DONE&&503===d.status&&c(Error("(503) Service is not available."))};d.withCredentials=!0;d.open(e,b);g&&d.setRequestHeader("Content-Type","application/x-www-form-urlencoded;");d.send(g||null)};this.resendEvent=function(){setTimeout(function(){b.resendCount<
b.maxResendCount?b.resendCount++:(b.q.pop(!1),b.resendCount=0);b.processEvents(!1)},1E3*(b.resendCount+1))};this.sendEvent=function(a){b.ccs&&b.send(b.ccs,a.toURLEncoded(),"POST",b.eventResponseHandler,null)};this.synthLoaded=function(a){b.synthLoad=a};this.processEvents=function(a){b.isReal(a)&&(b.sendLock=a);a=null;if(b.unlocked()&&(a=b.q.getFront())){b.sendLock=!0;var c=Date.now();a.paramMap.set("cts",c);a.paramMap.set("timestamp",b.serverTimestamp+c-b.clientBaseTimestamp);b.sendEvent(a)}};this.pushEvent=
function(a){b.q.push(a);b.unlocked()&&b.processEvents()};this.processIdentity=function(a,c,f,e){void 0===c&&(c=function(){});var d=b.persistenceService;f?(d.setIdentityEvent(f),b.latestIdentity=e):f=d.getIdentityEvent();if(f){var h="D"===f;b.call(a,function(a){c(a);if(b.latestIdentity===e||null==b.latestIdentity)d.removeIdentityEvent(),b.latestIdentity=null},void 0,h&&"DELETE"||"POST",h?null:f)}};this.send=function(a,c,f,e,g){var d=void 0;try{var h=b.initialTimeout*(b.resendCount+1);d=new XMLHttpRequest;
d.onreadystatechange=function(){e(d,g)};"function"===typeof d.onloadend&&(d.onloadend=function(){b.cancelTimer(d)});if("POST"==f)d.open(f,a,!0),d.timeout=h,d.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8"),(b.bodyInHeaderAll||b.bodyInHeaderLoad&&c&&-1<c.indexOf("event=load"))&&d.setRequestHeader("X-SI-EventBody",c),d.onloadstart=function(){d.ontimeout=function(){b.timeout(d)}};else{var n=null!=c?a.indexOf("?")?"&"+c:"?"+c:"";d.open(f,a+n,!0)}d.withCredentials=!0;
c+="&sndcts="+Date.now();var p=-1<c.indexOf("eventName=load");b.synthLoad&&(c=b.replaceParam(c,"session",b.sessionId),c=b.replaceParam(c,"hb",b.persistenceService.getSidArray()[2]),!p&&(c=b.replaceParam(c,"load_id",b.loadId)));(b.firstLoad||!p&&b.loadIdChanging)&&(c=b.replaceParam(c,"load_id",b.loadId));b.firstLoad&&p&&(b.firstLoad=!1);p&&-1==c.indexOf("load_id=")&&(b.loadIdChanging=!0);c+="&domain="+b.getDomain();d.send(c)}catch(x){d&&d.abort(),b.resendEvent()}};this.replaceParam=function(b,a,c){null==
c&&(c="");var d=new RegExp("\\b("+a+"=).*?(&|#|$)");if(0<=b.search(d))return b.replace(d,"$1"+c+"$2");b=b.replace(/[?#]$/,"");return b+"&"+a+"="+c};this.cancelTimer=function(b){b.timeout&&clearTimeout(b.timeout);b.ontimeout=null};this.eventResponseHandler=function(a){if(b.isReal(a.readyState)&&a.readyState==XMLHttpRequest.DONE)if(b.cancelTimer(a),200<=a.status&&300>a.status){if(-1<a.responseText.indexOf("load_id")){var c=void 0;try{c=JSON.parse(a.responseText),c.load_id&&b.setLoadId(c.load_id)}catch(f){}}else if(-1<
a.responseText.indexOf("sid")){b.notifyObservers();return}b.q.pop(!1);b.resendCount=0;b.processEvents(!1)}else a.abort(),b.resendEvent()};this.timeout=function(a,c){void 0===c&&(c=!0);a&&a.abort();c&&b.resendEvent()};this.q=a;this.persistenceService=c;(this.legacyTagLoaded=this.com_sas_ci_acs&&this.com_sas_ci_acs.ob_configure)&&this.com_sas_ci_acs.ob_configure.getLoadId()&&(this.firstLoad=!1)}e.prototype.setServerTimestamp=function(a){this.serverTimestamp=a};e.prototype.setClientBaseTimestamp=function(a){this.clientBaseTimestamp=
a};e.prototype.setFirstLoad=function(a){this.firstLoad=a};e.prototype.addObserver=function(a){this.observers.push(a)};e.prototype.setCachedLoadEvent=function(a){this.cachedLoadEvent=a};e.prototype.notifyObservers=function(){for(var a=0,c=this.observers;a<c.length;a++)(0,c[a])()};e.prototype.isReal=function(a){return"undefined"!=typeof a||null!=a};return e}();g.NetworkService=l})($ci360||($ci360={}));
(function(g){var l=function(){function e(a,c){var b=this;this.setExtTenantId=function(a){b.extTenantId=a};this.getUsrAgent=function(){return b.usrAgSh384||b.setUsrAgent(b.encodingService.sha384(navigator.userAgent||"").substring(0,30))};this.setUsrAgent=function(a){return b.usrAgSh384=a};this.REGULAR_EXPRESSIONS={INTEGER:"^[\\-]?\\d+$",DECIMAL:"^[0-9]+(.[0-9]{1,2})?$"};this.SPOT_DEP_EVENTS={clickthrough:"1",impression:"1",impressionViewable:"1"};this.SPOT_DEP_EVENT_KEYS={creativeId:"1",spotId:"1",
taskId:"1"};this.PARAMS_METADATA={cart:{action:{required:!0,regex:"^cartview$|^checkout$|^purchase$",internal_name:"cart_type"},uri:{required:!0,default_value:function(){return document.URL}},id:{types:["string","number"],regex:"^.{0,42}$",internal_name:"cart_id"},orderId:{types:["string","number"],internal_name:"order_id"},name:{internal_name:"cart_name"},billingCity:{regex:"^.{0,390}$",internal_name:"billing_city"},billingCountry:{regex:"^.{0,85}$",internal_name:"billing_country"},billingPostcode:{regex:"^.{0,10}$",
internal_name:"billing_postcode"},billingRegion:{regex:"^.{0,256}$",internal_name:"billing_region"},deliveryType:{regex:"^.{0,42}$",internal_name:"delivery_type"},paymentType:{regex:"^.{0,42}$",internal_name:"payment_type"},shippingCity:{regex:"^.{0,390}$",internal_name:"shipping_city"},shippingCost:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"shipping_cost"},shippingCountry:{regex:"^.{0,85}$",internal_name:"shipping_country"},shippingPostcode:{regex:"^.{0,10}$",
internal_name:"shipping_postcode"},shippingRegion:{regex:"^.{0,256}$",internal_name:"shipping_region"},tax:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL},totalCartValue:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"total_cart_value"},apiEventKey:{},cart_id_internal:{}},cartaction:{action:{required:!0,regex:"^add$|^addFailed$|^update$|^remove$"},availabilityMessage:{regex:"^.{0,650}$",internal_name:"availability_message"},cartId:{types:["string",
"number"],internal_name:"cart_id"},cartName:{internal_name:"cart_name"},cartType:{regex:"^cartview$|^checkout$",internal_name:"cart_type"},group:{regex:"^.{0,130}$",internal_name:"product_group"},productId:{types:["string","number"],group:"identificationGroup",regex:"^.{0,130}$",group_min:1,internal_name:"product_id"},productName:{group:"identificationGroup",regex:"^.{0,130}$",group_min:1,internal_name:"product_name"},productSku:{types:["string","number"],group:"identificationGroup",regex:"^.{0,100}$",
group_min:1,internal_name:"product_sku"},savingsMessage:{regex:"^.{0,650}$",internal_name:"savings_message"},shippingMessage:{regex:"^.{0,650}$",internal_name:"shipping_message"},quantity:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"product_quantity"},unitPrice:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"product_unit_price"},uri:{required:!0,default_value:function(){return document.URL}},apiEventKey:{}},cartitem:{id:{types:["string",
"number"],group:"cartItemGroup",regex:"^.{0,130}$",group_min:1,internal_name:"product_id"},name:{group:"cartItemGroup",regex:"^.{0,130}$",group_min:1,internal_name:"product_name"},sku:{types:["string","number"],group:"cartItemGroup",regex:"^.{0,100}$",group_min:1,internal_name:"product_sku"},quantity:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.INTEGER,internal_name:"product_quantity"},unitPrice:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"product_unit_price"},
group:{regex:"^.{0,130}$",internal_name:"product_group"},availabilityMessage:{regex:"^.{0,650}$",internal_name:"availability_message"},shippingMessage:{regex:"^.{0,650}$",internal_name:"shipping_message"},savingsMessage:{regex:"^.{0,650}$",internal_name:"savings_message"}},change:{pageTitle:{required:!0,default_value:function(){return document.title},internal_name:"page_title"},referrer:{required:!0,default_value:function(){return encodeURI(document.referrer)}},location:{},attempts:{required:!0,default_value:function(){return"1"},
internal_name:"form._o.attempts"},uri:{required:!0,default_value:function(){return document.URL}},id:{required:!0,internal_name:"form._o.id"},name:{internal_name:"form._h.name"}},click:{uri:{},anchorId:{types:["string","number"],internal_name:"anchor_id"},pageTitle:{required:!0,default_value:function(){return document.title},internal_name:"page_title"},title:{required:!1},referrer:{required:!0,default_value:function(){return encodeURI(document.referrer)}},anchorHref:{internal_name:"anchor_href"},
anchorName:{internal_name:"anchor_name"},elementTagName:{},location:{},onClick:{internal_name:"onclick"},targetInnerText:{},targetSelectorPath:{}},clickthrough:{uri:{required:!0,default_value:function(){return document.URL}},spotName:{required:!0},spotId:{required:!0,internal_name:"spot_id"},variantId:{internal_name:"variant_id"},creativeId:{required:!0,internal_name:"creative_id"},taskId:{required:!0,internal_name:"task_id"}},contentchange:{uri:{required:!0,default_value:function(){return document.URL}},
attributeName:{required:!1,internal_name:"attributename"},newValue:{required:!1,internal_name:"newvalue"},oldValue:{required:!1,internal_name:"oldvalue"},pageTitle:{required:!0,default_value:function(){return document.title},internal_name:"page_title"},id:{types:["string","number"],internal_name:"targetid"},name:{internal_name:"targetname"},selector:{required:!0,internal_name:"targetselector"},type:{required:!0,regex:"^attribute$|^childremove$|^childadd$",internal_name:"targettype"}},custom:{uri:{required:!0,
default_value:function(){return document.URL}},apiEventKey:{}},document:{altText:{internal_name:"targetInnerText"},id:{internal_name:"anchor_id"},url:{required:!0,internal_name:"anchor_href"},name:{internal_name:"anchor_name"},selectorPath:{internal_name:"targetSelectorPath"}},identity:{loginId:{required:!0,internal_name:"login_event",regex:".+"},loginEventType:{required:!0,regex:"^email_id$|^login_id$|^customer_id$|^subject_id$|^account_id$|^household_id$",internal_name:"login_event_type"},eventSource:{required:!1,
default_value:"webmarketing"}},impression:{eventSource:{required:!1,default_value:"webmarketing"},uri:{required:!0,default_value:function(){return document.URL}},spotName:{required:!0},creativeId:{required:!0,internal_name:"creative_id"},spotId:{required:!0,internal_name:"spot_id"},taskId:{required:!0,internal_name:"task_id"},variantId:{internal_name:"variant_id"}},impressionViewable:{uri:{required:!0,default_value:function(){return document.URL}},spotName:{required:!0},spotId:{required:!0,internal_name:"spot_id"},
variantId:{internal_name:"variant_id"},creativeId:{required:!0,internal_name:"creative_id"},taskId:{required:!0,internal_name:"task_id"}},internalSearch:{searchName:{required:!0},term:{required:!0,internal_name:"searchTerm"},resultsDisplayed:{regex:this.REGULAR_EXPRESSIONS.INTEGER},resultsDisplayFlag:{required:!0,regex:"^true$|^false$"},fieldId:{internal_name:"searchFieldId"},fieldName:{internal_name:"searchFieldName"},apiEventKey:{}},jsvarchange:{uri:{required:!0,default_value:function(){return document.URL}},
name:{required:!0},action:{default_value:"update",regex:"^add$|^update$"},oldValue:{required:!0,internal_name:"oldvalue"},newValue:{required:!0,internal_name:"newvalue"}},load:{uri:{required:!0,default_value:function(){return document.URL}},pageTitle:{required:!0,default_value:function(){return document.title},internal_name:"page_title"},referrer:{required:!0,default_value:function(){return encodeURI(document.referrer)}}},media:{uri:{required:!0,default_value:function(){return document.URL}},id:{required:!0,
internal_name:"player_id"},url:{required:!0,regex:"^.{0,260}$",internal_name:"media"},player:{required:!0,regex:"^.{0,30}$",internal_name:"media_player"},position:{required:!0,types:["string","number"],regex:this.REGULAR_EXPRESSIONS.INTEGER,internal_name:"media_position"},duration:{required:!0,types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"media_duration"},action:{required:!0,regex:"^start$|^stop$|^end$",internal_name:"media_action"}},productView:{id:{group:"identificationGroup",
group_min:1,internal_name:"product_id"},name:{group:"identificationGroup",group_min:1,internal_name:"product_name"},sku:{group:"identificationGroup",group_min:1,internal_name:"product_sku"},quantity:{internal_name:"product_quantity",regex:this.REGULAR_EXPRESSIONS.INTEGER},unitPrice:{internal_name:"product_unit_price",regex:this.REGULAR_EXPRESSIONS.DECIMAL},group:{internal_name:"product_group",regex:"^.{0,130}$"},availabilityMessage:{internal_name:"availability_message",regex:"^.{0,650}$"},shippingMessage:{internal_name:"shipping_message",
regex:"^.{0,650}$"},savingsMessage:{internal_name:"savings_message",regex:"^.{0,650}$"},apiEventKey:{}},promotion:{trackingCode:{},creativeName:{internal_name:"creative"},placementId:{},name:{required:!0,internal_name:"promotionName"},recordType:{required:!0,regex:"display|use"},type:{required:!0,internal_name:"promotionType"},apiEventKey:{}},submit:{attempts:{required:!0,default_value:function(){return"1"},internal_name:"form._o.attempts"},uri:{required:!0,default_value:function(){return document.URL}},
referrer:{required:!0,default_value:function(){return encodeURI(document.referrer)}},id:{required:!0,internal_name:"form._o.id"},location:{},name:{types:["number","string"],internal_name:"form._h.name"}},visibilityChange:{uri:{required:!0,default_value:function(){return document.URL}},hidden:{required:!0,regex:"^true$|^false$",default_value:function(){return document.hidden}}}};this.commonFieldHandling=function(a,c,f){var d=f.id||f.name,e=f.value,h="form.f."+d;if("true"===f.obscure){var k="ffobscure."+
++a.obscureCount;c[k]=h;e=b.encodingService.sha384(e+b.extTenantId)}a.paramMap.set(h,e);null!=f.type&&a.paramMap.set("form.f."+d+"._h.type",f.type);null!=f.alt&&a.paramMap.set("form.f."+d+"._h.alt",f.alt);null!=f.id&&a.paramMap.set("form.f."+d+"._h.id",f.id);null!=f.name&&a.paramMap.set("form.f."+d+"._h.name",f.name);null!=f.changes&&a.paramMap.set("form.f."+d+"._o.changes",f.changes)};this.obfuscateFields=function(a){var c=a.paramMap.get("obfuscateFields"),d=[];if(null!=c)try{d=JSON.parse(c)}catch(u){}for(c=
0;c<d.length;c++){var e=d[c],g=a.paramMap.get(e);if(null!=g){a.paramMap.set(e,b.encodingService.sha384(g+b.extTenantId));g="ffobscure."+ ++a.obscureCount;var m=a.paramMap.get("eventName");m=b.PARAMS_METADATA[m];var k=void 0;null!=m[e]&&(k=m[e].internal_name);a.paramMap.set(g,null!=k?k:e)}}a.paramMap.delete("obfuscateFields")};this.encodingService=a;this.util=c}e.prototype.mapTransportNames=function(a){var c=a.paramMap.get("eventName"),b=this.PARAMS_METADATA[c],d={impression:"spot_change",impressionViewable:"impression_viewable",
clickthrough:"spot_clicked",identity:"IdentityEvent",visibilityChange:"visibilitychange"},e;for(e in d)c===e&&a.paramMap.set("eventName",d[e]);for(var f in b)(c=b[f].internal_name)&&a.paramMap.has(f)&&(a.paramMap.set(c,a.paramMap.get(f)),a.paramMap.delete(f))};e.prototype.getParamsMetadata=function(){return this.PARAMS_METADATA};e.prototype.cartEventHandling=function(a,c){c=c.items;if(null!=c){var b;for(b=0;b<c.length;b++){var d=c[b],e=new g.CI360EventObj("cartitem"),f;for(f in d)d.hasOwnProperty(f)&&
e.paramMap.set(f,d[f]);if(this.validateEvent(e)){d=this.PARAMS_METADATA.cartitem;for(var n in d){var p=d[n].internal_name;p&&e.paramMap.has(n)&&(e.paramMap.set(p,e.paramMap.get(n)),e.paramMap.delete(n))}a.paramMap.set("cartitem."+(b+1),e.toURLEncoded())}}a.paramMap.set("cartitem_count",b)}};e.prototype.changeEventHandling=function(a,c){var b=c.field;null!=b&&(this.commonFieldHandling(a,c,b),delete c.field)};e.prototype.addFieldsToEvent=function(a,c){for(var b in c)c.hasOwnProperty(b)&&a.paramMap.set(b,
c[b])};e.prototype.submitEventHandling=function(a,c){var b=c.fields;if(null!=b){for(var d=0;d<b.length;d++)this.commonFieldHandling(a,c,b[d]);delete c.fields}};e.prototype.resolveDefaultVal=function(a,c){var b={types:["string"],regex:".*",required:!1};return void 0!==a?a:b[c]};e.prototype.addDefaultFields=function(a){var c=this.PARAMS_METADATA[a.paramMap.get("eventName")],b;for(b in c){var d=c[b];null!=d.default_value&&null==a.paramMap.get(b)&&("function"===typeof d.default_value&&(d.default_value=
d.default_value()),a.paramMap.set(b,d.default_value))}};e.prototype.validateEvent=function(a){if(""!==a.paramMap.get("datahub_id")){var c=a.paramMap.get("eventName");if(c){var b=this.PARAMS_METADATA[c];if(null!=b){var d=new Map;for(m in b){var e=b[m];if(this.resolveDefaultVal(e.required,"required")&&"spotName"!==m&&null==a.paramMap.get(m))return this.SPOT_DEP_EVENTS[c]&&this.SPOT_DEP_EVENT_KEYS[m]&&a.paramMap.get("spotName"),!1;var f=e.group;if(null!=f){var g=d.get(f);null==g&&d.set(f,{count:0,min:e.group_min})}}var p=
[];a.paramMap.forEach(function(b,a){p.push(a)});for(c=0;c<p.length;c++){var m=p[c];f=a.paramMap.get(m);m=b[m];if(null!=m){if(!(new RegExp(this.resolveDefaultVal(m.regex,"regex"))).test(f)&&m.required)return!1;null!=m.group&&(f=m.group,g=d.get(f),g.count++)}}var k=!0,u="";d.forEach(function(b,a){b.count<b.min&&(u+=a+", ",k=!1)});return k?!0:(u=u.slice(0,u.length-2),!1)}}}return!1};return e}();g.ParamService=l})($ci360||($ci360={}));
(function(g){var l=function(){function e(){var a=this;this.VID_PREF="_SI_VID_1.";this.SID_PREF="_SI_SID_1.";this.DID_PREF="_SI_DID_1.";this.TAB_PREF="_ciutbid_";this.ID_PREF="_ciaid_";this.storage="sessionStorage";this.setExtTenantId=function(c){a.extTenantId=c};this.setSld=function(c){a.sld=c};this.vidName=function(){return a.VID_PREF+a.extTenantId};this.sidName=function(){return a.SID_PREF+a.extTenantId};this.didName=function(){return a.DID_PREF+a.extTenantId};this.setCookieOnSLDs=function(c,b,
d){if(null!=b&&b!=a.getCookie(c))if(a.sld){var e=a.sld.split(","),f;for(f in e)if(a.getCookie(c)!=b)a.setCookie(c,b,d,e[f]);else break}else a.setCookie(c,b,d)};this.setCookie=function(a,b,d,e){var c=";";if(null!=d){var h=new Date;h.setTime(h.getTime()+(0<d?864E5*d:31536E6));c+="expires="+h.toUTCString()}document.cookie=a+"="+b+c+";path=/"+(null==e?"":"; domain="+e)};this.getCookie=function(a){return(a=document.cookie.match("(^|;)\\s*"+a+"\\s*=\\s*([^;]+)"))?a.pop():""};this.setVid=function(c){a.setCookieOnSLDs(a.vidName(),
c,0)};this.getVid=function(){return a.getCookie(a.vidName())};this.setSid=function(c){if(c){var b=(new Date).getTime(),d=a.getSidArray();d=d[0]==c?Math.max(b-Number(d[1]),Number(d[2])):null;a.setCookieOnSLDs(a.sidName(),c+"."+b+"."+(d||0),null)}};this.getSidArray=function(){var c=a.getCookie(a.sidName());return c&&(c=c.split("."),2<c.length)?c:["","0","0"]};this.setDid=function(c){a.setCookieOnSLDs(a.didName(),c,null)};this.getDid=function(){return a.getCookie(a.didName())};this.registerActivity=
function(){a.setSid(a.getSidArray()[0])};this.getTabId=function(){var c=g[a.storage].getItem(a.TAB_PREF);c||(c=Math.floor(1E12*Math.random()+1).toString(),g[a.storage].setItem(a.TAB_PREF,c));return c};this.getIdentityEvent=function(){return g[a.storage].getItem(a.ID_PREF+a.extTenantId)};this.setIdentityEvent=function(c){c&&g[a.storage].setItem(a.ID_PREF+a.extTenantId,c)};this.removeIdentityEvent=function(){g[a.storage].removeItem(a.ID_PREF+a.extTenantId)}}e.prototype.getCookies=function(){for(var a=
document.cookie.split(";"),c={},b=0;b<a.length;b++){var d=a[b].split("="),e=(d[0]+"").trim();c[e]=unescape(d[1])}return c};return e}();g.PersistenceService=l})($ci360||($ci360={}));
(function(g){(function(){var l={sessionStorage:"sessionStorage",localStorage:"localStorage"},e;for(e in l)(function(a){try{var c=window[a];c.setItem("a","b");c.getItem("a");c.removeItem("a");return!1}catch(b){return!0}})(e)?g[l[e]]={_data:{},setItem:function(a,c){return this._data[a]=String(c)},getItem:function(a){return this._data.hasOwnProperty(a)?this._data[a]:void 0},removeItem:function(a){return delete this._data[a]},clear:function(){return this._data={}}}:g[l[e]]=window[e]})()})($ci360||($ci360=
{}));
(function(g){var l=function(){function e(a,c){var b=this;this.spotNamesToIdsMap=new Map;this.tmpSpotNamesToIdsMap=new Map;this.buildSpotDefUrl=function(a){var c=a.domain||window.location.hostname||b.networkService.getDomain(),d=a.path||window.location.pathname;if(a.params){var e=[],g;for(g in a.params)e.push(encodeURIComponent(g)+"="+encodeURIComponent(a.params[g]));a=e.join("&");a=encodeURIComponent(a.replace(/[!'()*]/g,function(b){return"%"+b.charCodeAt(0).toString(16).toUpperCase()}))}else a=window.location.search;
return b.isConfigValid()?b.config.sdu+"?domain="+c+"&p="+d+"&params="+a:""};this.cachedSpotDefinitions={};this.getSpotDefsInternal=function(a,c,e){if(b.isConfigValid())if(c){var d=new XMLHttpRequest;d.onreadystatechange=function(){if(d.readyState===XMLHttpRequest.DONE&&200===d.status){var a=[];d.responseText&&(a=JSON.parse(d.responseText));b.cachedSpotDefinitions=a;e(null,a)}else d.readyState===XMLHttpRequest.DONE&&e(Error("Spot definitions could not be retrieved: "+d.statusText),null)};d.open("GET",
b.buildSpotDefUrl(a));d.send()}else e(null,b.cachedSpotDefinitions)};this.getSpotDefinitions=function(a,c){b.getSpotDefsInternal(a,!0,function(b,d){var e=new Map;if(!b){for(var f=[],h=0;h<d.length;h++){var g=d[h];if("spotSet"===g.spotType&&(!a.names||a.names&&-1<a.names.indexOf(g.spotName))){var n=0;for(g=g.spotList;n<g.length;n++)f.push(g[n])}}for(h=0;h<d.length;h++)g=d[h],"spot"===g.spotType&&(!a.names||a.names&&-1<a.names.indexOf(g.spotName))||-1<f.indexOf(g.spotId)?e.set(g.spotName,{id:g.spotId,
selector:g.selector,attributes:g.spotAttributes}):"jsSpot"===g.spotType&&e.set(g.spotName,{id:g.spotId,selector:null,attributes:g.spotAttributes})}c(b,e)})};this.getCreativesUrls=function(a,c,f){var d=a.domain||window.location.hostname||b.networkService.getDomain();b.getSpotDefsInternal(a,c,function(c,h){if(!c&&b.isConfigValid()){c=b.config.csu.replace("hserver","bserverj");c=c+"/ball/domain="+d;c+="/customerid="+b.configService.getDatahubId();c+="/sessionid="+(a.sid||b.config.sid);c+="/hint=x";for(var k=
0,n=[],m=new Map,p=[],l=c,w=[],q=b.getViewId(),C=new Map,y=0;y<h.length;y++){var t=h[y];if("spotSet"===t.spotType&&(!a.names||a.names&&-1<a.names.indexOf(t.spotName))){var G=b.getViewId(),D=0;for(t=t.spotList;D<t.length;D++){var N=t[D];p.push(N);C.set(N,G)}}else b.tmpSpotNamesToIdsMap.set(t.spotName,{spotId:t.spotId}),C.set(t.spotId,q)}for(y=0;y<h.length;y++)if(t=h[y],("spot"===t.spotType||"jsSpot"===t.spotType)&&(!a.names||a.names&&-1<a.names.indexOf(t.spotName))||-1<p.indexOf(t.spotId)){l.length>
e.MAX_URL_SIZE&&(m.set(l,n),w.push(l),k=0,n=[],l=c);n.push(""+t.spotName);G="";q=void 0;a.attributes&&(q=a.attributes[t.spotName]);if(q)for(var z in q)"product_id"===z||"product_sku"===z?(z+="_key",G+=z+"="+q[z]+".trim()/"):null!=q[z]&&b.containsAttribute(t.spotAttributes,z)&&(D=q[z],D.toString&&(G+=z+"="+g.Base64.encode(D.toString().trim()).replace(/=/g,"")+"/"));l+="/b"+ ++k+"/spot_id="+t.spotId+"/"+G+"viewid="+C.get(t.spotId)}n.length&&(m.set(l,n),w.push(l));f(null,w,m)}else f(c,null,null)})};
this.configService=a;this.networkService=c}e.prototype.init=function(a){this.config=this.configService.getConfig();a()};e.prototype.isConfigValid=function(){return!(!this.config||!this.config.sdu)};e.prototype.handleCreativesUrlResponse=function(a,c,b){return function(){if(a.readyState===XMLHttpRequest.DONE&&200===a.status){var d=[];if(a.responseText)try{d=JSON.parse(a.responseText)}catch(h){b(Error("Creatives response could not be parsed: "+h),c,null)}b(null,c,d)}else a.readyState===XMLHttpRequest.DONE&&
b(Error("Creatives could not be retrieved: "+a.statusText),c,null)}};e.prototype.getCreatives=function(a,c,b){var d=this;this.getCreativesUrls(a,c,function(a,c,e){if(a)b(a,null);else{var f=new Map,h=0,g=!0;a=function(a,c,k){if(!a&&g){h++;var n=a=0;c=e.get(c);for(var l=0;l<k.length;l++){var m=k[l],p=c[a++],q=d.parseCreative(m);f.set(p,q);n+=d.addSpotNameToIds(p,m)}h===e.size&&(d.deleteSpotNamesToIds(n),b(null,f))}else g&&(g=!1,b(a,null))};if(e.size)for(var n=0;n<c.length;n++){var l=c[n],x=new XMLHttpRequest;
x.onreadystatechange=d.handleCreativesUrlResponse(x,l,a);x.open("GET",l);x.send()}else b(null,new Map)}})};e.prototype.getPersonalizedCreative=function(a,c){var b=this;a.delay=a.delay||e.DELAY;a.retries=null!=a.retries?a.retries:e.RETRIES;this.getCreatives(a,!0,function(d,e){d?c(d,null):1===e.size?e.forEach(function(d){d.creativeId?c(null,d):1>--a.retries?c(null,null):setTimeout(function(a,c){b.getPersonalizedCreative(a,c)},a.delay,a,c)}):0===e.size?c(Error("No creative found"),null):1<e.size&&c(Error("More than one creative found"),
null)})};e.prototype.addSpotNameToIds=function(a,c){var b=0;(c=this.parseCreative(c))&&c.creativeId&&c.taskId&&(b++,a=this.tmpSpotNamesToIdsMap.get(a))&&(a.creativeId=c.creativeId,a.taskId=c.taskId,a.variantId=c.variantId);return b};e.prototype.parseCreative=function(a){var c={content:a.replace(/<data .*<\/data>/,"").replace(/<data .*?\/>/,"")},b=a.match(/data-creativeID="([A-Za-z0-9-]+)"/i);b&&b[1]&&(c.creativeId=b[1],(b=a.match(/data-taskID="([A-Za-z0-9-]+)"/i))&&b[1]&&(c.taskId=b[1],(a=a.match(/data-variant_id="([A-Za-z0-9-]+)"/i))&&
a[1]&&(c.variantId=a[1])));return c};e.prototype.deleteSpotNamesToIds=function(a){var c=this,b=this.spotNamesToIdsMap.size-e.MAX_SPOT_NAMES_TO_CACHE+a;if(0<b){var d=0;this.spotNamesToIdsMap.forEach(function(a,c,e){d++<b&&e.delete(c)})}this.tmpSpotNamesToIdsMap.forEach(function(a,b){a.creativeId&&c.spotNamesToIdsMap.set(b,a)});this.tmpSpotNamesToIdsMap.clear()};e.prototype.decorateEvent=function(a){var c=a.paramMap.get("eventName");if("clickthrough"===c||"impression"===c||"impressionViewable"===c)if(c=
this.spotNamesToIdsMap.get(a.paramMap.get("spotName")))a.paramMap.set("spotId",c.spotId),a.paramMap.set("taskId",c.taskId),a.paramMap.set("creativeId",c.creativeId),c.variantId&&a.paramMap.set("variantId",c.variantId),a.paramMap.delete("spotName")};e.prototype.getViewId=function(){return Math.floor(1E12*Math.random()+1).toString()};e.prototype.containsAttribute=function(a,c){for(var b=0;b<a.length;b++)if(a[b].name===c)return!0};e.MAX_URL_SIZE=1800;e.MAX_SPOT_NAMES_TO_CACHE=1E4;e.DELAY=1E3;e.RETRIES=
30;return e}();g.SpotService=l})($ci360||($ci360={}));
(function(g){var l=function(){function e(){var a=this;this.extractParam=function(c,b){return b&&c&&(c=a.getUriInfoGeneric(b).searchObj[c])?c.replace(/\+/g," "):null};this.getJsVarValueSafe=function(a){var b=window;a.split(".").forEach(function(a){b=b&&b[a]});return b&&b.toString()||null};this.polyfill()}e.prototype.polyfill=function(){Element.prototype.matches||(Element.prototype.matches=Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector)};e.prototype.isSelectorValid=function(a){var c=
document.createElement("br");a:{try{c.querySelector(a)}catch(b){a=!1;break a}a=!0}return a};e.prototype.getElementAncestor=function(a,c){for(;a.parentElement;){var b=a.parentElement;if(b.matches(c))return b;a=a.parentElement}return null};e.prototype.querySelectorShadow=function(a,c){c=c.split("&&");try{for(var b=0;b<c.length;b++)a=a!==document.body&&a.shadowRoot?a.shadowRoot.querySelector(c[b]):a.querySelector(c[b])}catch(d){}return a};e.prototype.extractDomain=function(a){try{var c=a.match(/^\s*\S+?:\/\/([^\/:?#]+)(?:[\/:?#]|$)/i);
return c&&c[1]}catch(b){return null}};e.prototype.remove=function(a,c){for(var b=0;b<c.length;b++)a=a.replace(new RegExp("(&?)"+c[b]+"=.*?(&|$)","g"),function(a,b,c){return b&&c});return a};e.prototype.getUriInfoGeneric=function(a){var c=document.createElement("a");c.href=a;a="";for(var b=this.remove(c.search.substring(1),["_ga","adobe_mc"]),d=b.split("&"),e={},f=0;f<d.length;f++){var g=d[f].split("=");"_ci_"===g[0]?a=g[1]:e[decodeURIComponent(g[0])]=decodeURIComponent(g[1]||"")}b=this.remove(b,["_ci_"]);
return{protocol:c.protocol.replace(":",""),host:c.hostname,port:c.port,path:("/"!==c.pathname.charAt(0)?"/":"")+c.pathname,search:b,searchObj:e,cdt:a}};e.prototype.getUriInfo=function(){return this.getUriInfoGeneric(document.URL)};e.prototype.getMeta=function(a){for(var c=document.getElementsByTagName("meta"),b=c.length,d=0;d<b;d++)if(c[d].getAttribute("name")===a)return c[d].getAttribute("content");return""};e.prototype.getMetas=function(){for(var a=document.getElementsByTagName("meta"),c={},b=a.length,
d=0;d<b;d++){var e=a[d],f=e.getAttribute("name");f&&(c[f]=e.getAttribute("content"))}return c};e.prototype.getDataAttributes=function(a){a=a.dataset;var c={},b;for(b in a)c[b]=a[b];return c};e.prototype.nextChar=function(a,c,b){var d=a.indexOf(c);a=a.indexOf(b);return-1===d&&-1==a?"":-1===d?b:-1===a?c:d<a?c:b};e.prototype.tokenizeObjectString=function(a){for(var c=[];0<a.length;){var b=a.indexOf("."),d=a.indexOf("[");if(0!==b&&0!==d){var e=this.nextChar(a,".","[");"."===e?(c.push(a.substring(0,b)),
a=a.slice(b)):"["===e?(c.push(a.substring(0,d)),a=a.slice(d)):(c.push(a),a="")}else 0===b?(a=a.slice(1),e=this.nextChar(a,".","["),""!==e?(d=a.indexOf(e),c.push(a.substring(0,d)),a=a.slice(d)):(c.push(a),a="")):0===d?(b=a.charAt(1),"'"===b||'"'===b?(d+=1,b=a.charAt(d),b=a.slice(d+1).indexOf(b)+d+1,e=b+1,c.push(a.substring(d+1,b))):(e=a.indexOf("]"),c.push(a.substring(1,e))),a=a.slice(e+1)):a=""}return c};e.prototype.getVariableFromObjectString=function(a){for(var c=a.length,b=0,d=window;null!=d&&
b<c;)d=d[a[b++]];return b&&b===c?d:void 0};e.prototype.debounce=function(a,c,b){function d(b){var c=m,d=k;m=k=void 0;M=b;return u=a.apply(d,c)}function e(a){var b=a-x;a-=M;return void 0===x||b>=c||0>b||q&&a>=y}function f(){var a=Date.now();if(e(a))return g(a);var b=a-M;a=c-(a-x);r=setTimeout(f,q?Math.min(a,y-b):a)}function g(a){r=void 0;if(C&&m)return d(a);m=k=void 0;return u}function l(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];b=Date.now();var g=e(b);m=a;k=this;x=b;if(g){if(void 0===
r)return M=a=x,r=setTimeout(f,c),w?d(a):u;if(q)return r=setTimeout(f,c),d(x)}void 0===r&&(r=setTimeout(f,c));return u}void 0===c&&(c=0);var m,k,u,r,x,M=0,w=!1,q=!1,C=!0;if("function"!==typeof a)throw new TypeError("Expected a function");if(b){w=!!b.leading;var y=(q="maxWait"in b)?Math.max(+b.maxWait||0,c):y;C="trailing"in b?!!b.trailing:C}l.flush=function(){return void 0===r?u:g(Date.now())};l.pending=function(){return void 0!==r};return l};e.prototype.throttle=function(a,c,b){var d=!0,e=!0;if("function"!==
typeof a)throw new TypeError("Expected a function");b&&(d="leading"in b?!!b.leading:d,e="trailing"in b?!!b.trailing:e);return this.debounce(a,c,{leading:d,trailing:e,maxWait:c})};e.prototype.filterElemsBySelector=function(a,c){for(var b=[],d=0;d<c.length;d++){a instanceof HTMLElement&&a.matches(c[d])&&b.concat(a);for(var e=a.querySelectorAll(c[d]),f=e.length,g=0;g<f;g++)b=b.concat(e[g])}return b};return e}();g.Util=l})($ci360||($ci360={}));
(function(g){var l=new g.Util,e=new g.Bootstrap,a=new g.PersistenceService,c=new g.LocalQueue("ciq2_","sessionStorage");c=new g.NetworkService(c,a);var b=new g.EncodingService;b=new g.ParamService(b,l);var d=new g.ConfigService(a,c,b,l),h=new g.SpotService(d,c);l=new g.EventService(d,a,c,b,h,l);e.require(d,h);e.createApi(d,b,l,h);d.setEnvironmentAttributes(e.getEnvironmentAttributes());e.setLazyInit(g.lazyInit);e.initialize()})($ci360||($ci360={}));
