name: Scrap transfers on transparent accounts

on:
  workflow_dispatch:
  schedule:
    - cron: '23 2 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install puppeteer
        run: npm i puppeteer

      - name: Scrape transfers on main account
        run: node src/scraper-ano.js 4070217
        
      - name: Scrape transfers on account for parliamentary election
        run: node src/scraper-ano.js 4090453

      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push